name: mongol_code_converter
description: A Unicode code conversion utility for Flutter

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mongol_code: ^0.3.0
  mongol: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: menksoft
      fonts:
        - asset: assets/fonts/MQG8F02.ttf