name: mongol_code_converter
description: A Unicode code conversion utility for Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mongol_code: ^0.3.0-nullsafety.0
  mongol: ^1.1.0
  get_it: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: menksoft
      fonts:
        - asset: assets/fonts/MQG8F02.ttf